apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}

          envFrom:
            - secretRef:
                name: vocabulary-env-from-vault

            # - secretRef:
            #     name: vocabulary-env
            # - secretRef:
            #     name: auth0-env

          resources: {}

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${APPLICATION_NAME}
  ports:
    - port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt

    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Vocabulary
    gethomepage.dev/icon: mdi-book-alphabet
    gethomepage.dev/group: 1P
spec:
  tls:
    - hosts:
        - ${K8S_INGRESS_HOST}
      secretName: ${APPLICATION_NAME}
  rules:
    - host: ${K8S_INGRESS_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${APPLICATION_NAME}
                port:
                  number: 3000
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vocabulary-env
spec:
  refreshInterval: 5m0s
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: vocabulary-env-from-vault
    creationPolicy: Orphan
  dataFrom:
    - extract:
        key: vocabulary
  data:
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: keycloak-main-client
        property: CLIENT_ID
    - secretKey: OIDC_AUTHORITY
      remoteRef:
        key: keycloak-main-client
        property: ISSUER
